puts "whats your message?"
answer = gets.chomp

answer.each_char do |i|
	if i == "a"
		print ".-,"
	elsif i == "b"
		print "-...,"
	elsif i == "c"
		print "-.-.,"
	elsif i == "d"
		print "-..,"
	elsif i == "e"
		print ".,"
	elsif i == "f"
		print "..-.,"	
	elsif i == "g"
		print "--.,"
	elsif i == "h"
		print "....,"
	elsif i == "i"
		print "..,"
	elsif i == "j"
		print ".---,"
	elsif i == "k"
		print "-.-,"
	elsif i == "l"
		print ".-..,"
	elsif i == "m"
		print "--,"	
	elsif i == "n"
		print "-.,"	
	elsif i == "o"
		print "---,"	
	elsif i == "p"
		print ".--.,"	
	elsif i == "q"
		print "--.-,"
	elsif i == "r"
		print ".-.,"
	elsif i == "s"
		print "...,"
	elsif i == "t"
		print "-,"	
	elsif i == "u"
		print "..-,"		
	elsif i == "v"
		print "...-,"
	elsif i == "w"
		print ".--,"
	elsif i == "x"
		print "-..-,"	
	elsif i == "y"
		print "-.--,"
	elsif i == "z"
		print "--..,"	
	elsif i == " "
		print " ,"
	elsif i == "."
		print "   "			
	end	
	end